### ISSUE TITLE
JIT-enabled SpiderMonkey 115.x fails GJS 1.78 tests

### ISSUE THREAD

**Issue by xen0n** [loongson-community/discussions#1]
Causing GNOME3 session to fail to start, among other undiscovered issues.

* [ ] Gentoo bug w/ error logs

**Comment by xry111** [comment]
For now a workaround may be disabling JIT in gjs, by calling `JS::DisableJitBackend()` before creating the first context/runtime (and before `JS_Init*`).

**Comment by xry111** [comment]
By the way, does `make -C js/src check-jit-test JITTEST_EXTRA_ARGS="--timeout 300 -j6"` in SpiderMonkey succeed?  Replace "6" with floor(the amount of available memory / 3GB).

**Comment by xen0n** [comment]
Triage: `dev-lang/spidermonkey-115.14.0` with `USE=jit` unmasked and enabled passes all tests, and `dev-libs/gjs-1.80.2` passes tests with it. Maybe it's just some petty toolchain or mozjs bugs that got fixed in the meantime.

Closing :tada:

**Comment by xen0n** [comment]
SpiderMonkey JIT is [now enabled](https://github.com/gentoo/gentoo/commit/a7dd224ff8cb7bdab44fb3dc043b5cfbe4b25264) in Gentoo.
