### ISSUE TITLE
[GCC] unrecognizable insn while building Skia

### ISSUE THREAD

**Issue by xen0n** [loongson-community/discussions#11]
cross-linking https://github.com/xen0n/loongson-overlay/issues/35

maybe this has been fixed in trunk but I can't recall any detail regarding this off my head.

**Comment by xen0n** [comment]
cc @xry111 do you have any idea? (At worst I'd put `-mno-lsx -mno-lasx` into CFLAGS/CXXFLAGS to inhibit SIMD codegen and workaround this for now.)

**Comment by xry111** [comment]
Is it reproducible with non-LTO?

**Comment by xen0n** [comment]
> Is it reproducible with non-LTO?

I just confirmed that this is the case.

**Comment by xen0n** [comment]
@xry111 FYI: I've minimized it at https://github.com/xen0n/loongson-overlay/issues/35#issuecomment-1805595389.

**Comment by xen0n** [comment]
I've also filed https://gcc.gnu.org/bugzilla/show_bug.cgi?id=112476.

**Comment by xry111** [comment]
It should be fixed now.

**Comment by xen0n** [comment]
Thanks!
