### ISSUE TITLE
[Rust] loongarch64-unknown-linux-musl target

### ISSUE THREAD

**Issue by heiher** [loongson-community/discussions#13]
由于当前musl loongarch64 port的补丁还没有进入上游，Rust loongarch64-unknown-linux-musl target的上游工作暂不可开展。创建一个讨论贴用于汇总早期工作，方便沟通互动和暴露问题。

* ~~musl v8: https://github.com/heiher/musl/commits/loongarch64~~ (已进上游)
* rust loongarch64-linux-musl: https://github.com/heiher/rust/commits/musl
* rust libc: https://github.com/heiher/libc/commits/musl
* rust compiler-builtins: https://github.com/heiher/compiler-builtins/commits/musl

**Comment by heiher** [comment]
Musl 1.2.5发布，已包含 LoongArch 支持： https://git.musl-libc.org/cgit/musl/log/?h=v1.2.5

**Comment by heiher** [comment]
Rust loongarch64-unknown-linux-musl 开始提交：

compiler-builtins: https://github.com/rust-lang/compiler-builtins/pull/579
libc: https://github.com/rust-lang/libc/pull/3605 https://github.com/rust-lang/libc/pull/3606
rust: https://github.com/rust-lang/rust/pull/121832

crosstool-ng: https://github.com/crosstool-ng/crosstool-ng/pull/2118 https://github.com/crosstool-ng/crosstool-ng/pull/2119 https://github.com/crosstool-ng/crosstool-ng/pull/2120

**Comment by xen0n** [comment]
https://github.com/rust-lang/rust/issues/122592

**Comment by heiher** [comment]
Tracking in https://github.com/rust-lang/rust/issues/122592
