### ISSUE TITLE
`am*_db.x` vs `am*.x + dbar` for acquire or release memory orders

### ISSUE THREAD

**Issue by xry111** [loongson-community/discussions#14]
For example: `__atomic_exchange_n(p, v, __ATOMIC_ACQUIRE);`

Is it better to use  `amswap.w` then `dbar 0b10100` instead of `amswap_db.w`?

Cc @heiher

**Comment by heiher** [comment]
We did a performance comparison in JVM, and there was almost no difference on LA664. This is not meant to apply to other cases.

**Comment by xry111** [comment]
Ok, so continue to using amswap_db for now as it's shorter.
