### ISSUE TITLE
英雄帖：Make Podman work on LoongArch

### ISSUE THREAD

**Issue by xen0n** [loongson-community/discussions#39]
Most deps are already working on LoongArch, but notably some are missing:

* [netavark](https://github.com/containers/netavark): blocked by several deps pulling in `nix < 0.27.0`
    * [mozim](https://github.com/nispor/mozim): needs non-trivial porting work (heavy use of `RawFd` etc. that got removed from nix 0.27)
    * `xdg-home`
    * `zbus`

more TODO

**Comment by cathay4t** [comment]
mozim 0.2.3 should works now.

**Comment by cathay4t** [comment]
And netavark 1.10.3 is using nix 0.27 now: https://github.com/containers/netavark/blob/v1.10.3/Cargo.toml#L46

**Comment by xry111** [comment]
zbus 4.1.0 is using nix-0.27 now as well.

**Comment by cheese** [comment]
netavark 新版本发布 https://github.com/containers/netavark/releases/tag/v1.11.0 ，不再间接依赖 nix-0.26，在 LoongArch 构建成功

**Comment by xen0n** [comment]
Podman 5.1.1 builds on Gentoo.

Closing; runtime problems are to be reported separately. ;-)
