### ISSUE TITLE
英雄帖: Port memtest86+ to LoongArch

### ISSUE THREAD

**Issue by xen0n** [loongson-community/discussions#5]
This is for coordination between potential porters who may simultaneously step up, to port [memtest86+](https://github.com/memtest86plus/memtest86plus) to LoongArch.

Note: according to upstream issues memtest86plus/memtest86plus#147 and memtest86plus/memtest86plus#285, this port would *not* get mainlined in the foreseeable future, due to maintenance burden and impossibility to test on their side. However, the upstream *does* favor a separately maintained fork -- meaning the porter would become the upstream for the resulting port.

**Comment by yetist** [comment]
已经开始研究了

**Comment by kilaterlee** [comment]
> 已经开始研究了

https://github.com/loongson/Firmware/tree/main/Memtest86%2B

**Comment by xry111** [comment]
上游已经合并了，应该可以关掉了？

**Comment by xen0n** [comment]
是的捏

For the record: use a very recent binutils to compile this.

**Comment by xen0n** [comment]
(late) integration into Gentoo: https://github.com/gentoo/gentoo/pull/40321
