### ISSUE TITLE
Investigate BFD linker crashes possibly related to TLSDESC

### ISSUE THREAD

**Issue by xen0n** [loongson-community/discussions#64]
Example: [Debian `mesa 24.2.0-2` build crash](https://buildd.debian.org/status/fetch.php?pkg=mesa&arch=loong64&ver=24.2.0-2&stamp=1723705806&raw=0)

This may be linked to the usage of TLSDESC, but I'm not sure at present.

On Gentoo I also noticed bus errors linking something while building `sys-libs/glibc`, with `-mtls-dialect=desc` globally set. On another box without TLSDESC enabled, glibc built without problems, so this is again highly suspect.

**Comment by xry111** [comment]
When I built Glibc with `-mtls-dialect=desc` there was no strange crashes.  Note that the Glibc library code is built with `-ftls-model=initial-exec` so only some tests use TLS descriptor.

**Comment by xen0n** [comment]
Important finding: I have specifically enabled additional `CFLAGS` for source debugging for glibc -- namely `-ggdb3`.

These `CFLAGS` work:

* `-O2 -pipe -march=la464 -mtune=la464 -mtls-dialect=desc`
* `-O2 -pipe -march=la464 -mtune=la464 -mtls-dialect=desc -g`
* `-O2 -pipe -march=la464 -mtune=la464 -mtls-dialect=desc -ggdb`
* `-O2 -pipe -march=la464 -mtls-dialect=desc -ggdb`
* `-O2 -pipe -march=loongarch64 -ggdb3`
* `-O2 -pipe -march=la464 -ggdb3`

These don't:

* `-O2 -pipe -march=la464 -mtls-dialect=desc -ggdb3`
* `-O2 -pipe -march=loongarch64 -mtls-dialect=desc -ggdb3`

So it's the combination of `-mtls-dialect=desc -ggdb3` that produces the object code eventually crashing the BFD linker. Not related to code generation.

**Comment by xry111** [comment]
Is there a reduced test case (one or several .s file(s))?

**Comment by ywgrit** [comment]
This issue has been fixed, refefence:https://patchwork.sourceware.org/project/binutils/patch/20240906010012.910300-1-wangxin03@loongson.cn/

**Comment by xen0n** [comment]
> This issue has been fixed, refefence:https://patchwork.sourceware.org/project/binutils/patch/20240906010012.910300-1-wangxin03@loongson.cn/

I can confirm it's fixing my local `ld` crashes of glibc and qtmultimedia, thanks!

(BTW: next time you could include a link to the context when submitting your changes, e.g. bugs fixed by the change, like this one. This will make it more likely for downstream people to recognize the value of your patch and cherry-pick it. Also, including a test case would be super useful.)

**Comment by xen0n** [comment]
For the record: so far the commit https://github.com/bminor/binutils-gdb/commit/28489a70d4660d67e71d75e82286a6e1a7003b93 is not present in the binutils 2.43 branch nor any tagged upstream release. Packagers would have to integrate it downstream.

**Comment by ywgrit** [comment]
> > This issue has been fixed, refefence:https://patchwork.sourceware.org/project/binutils/patch/20240906010012.910300-1-wangxin03@loongson.cn/
> 
> I can confirm it's fixing my local `ld` crashes of glibc and qtmultimedia, thanks!
> 
> (BTW: next time you could include a link to the context when submitting your changes, e.g. bugs fixed by the change, like this one. This will make it more likely for downstream people to recognize the value of your patch and cherry-pick it. Also, including a test case would be super useful.)

Yeah.
