### ISSUE TITLE
rust无法构建

### ISSUE THREAD

**Issue by Xinmudotmoe** [loongson-community/discussions#68]
# 错误信息
```log
rustc: /var/tmp/portage/sys-devel/llvm-18.1.8-r4/work/llvm/include/llvm/Support/Casting.h:578: decltype(auto) llvm::cast(From*) [with To 
= IntegerType; From = const Type]: Assertion `isa<To>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
```
# 复显步骤
```bash
# USE="profiler system-bootstrap system-llvm" emerge -vq rust
# 已知 与profiler system-bootstrap system-llvm 三个use均无关
# 目前测试与gentoo的rust patch无关
```

# 日志
[build.log.gz](https://github.com/user-attachments/files/17109186/build.log.gz)

**Comment by heiher** [comment]
看上去应该还是Rust前端与LLVM的配合有问题。使用`src/ci/docker/run.sh`构建也有类似的错误，且仅loongarch64复现，需要加`DEPLOY=1`的环境变量不开启LLVM的asseration。我这调试一下看看。

**Comment by xry111** [comment]
能用 `coredumpctl` 打一个 stack trace 吗？

**Comment by Xinmudotmoe** [comment]
> 能用 `coredumpctl` 打一个 stack trace 吗？

有的

[rustc.stack.txt](https://github.com/user-attachments/files/17115202/rustc.stack.txt)

**Comment by heiher** [comment]
试试这个补丁是否已经解决问题： https://github.com/llvm/llvm-project/commit/63267ca9016aa334b329aa408716456b4e3799c8

**Comment by Xinmudotmoe** [comment]
> 试试这个补丁是否已经解决问题： [llvm/llvm-project@63267ca](https://github.com/llvm/llvm-project/commit/63267ca9016aa334b329aa408716456b4e3799c8)

经过测试, 同样环境下编译rust-1.81.0, 并对照.
此补丁可以解决问题(Source compiled.)

**Comment by heiher** [comment]
LLVM issue: https://github.com/llvm/llvm-project/issues/109901

**Comment by xen0n** [comment]
Fixed with https://github.com/llvm/llvm-project/commit/63267ca9016aa334b329aa408716456b4e3799c8.
