### ISSUE TITLE
英雄帖：Add LoongArch SIMD support to xxHash

### ISSUE THREAD

**Issue by xen0n** [loongson-community/discussions#72]
Project: https://github.com/Cyan4973/xxHash

It could be beneficial to have this algorithm LoongArch-SIMD-accelerated.

[*The unofficial LoongArch intrinsics guide*](http://jia.je/unofficial-loongarch-intrinsics-guide/) is the place to learn LoongArch SIMD without having to consult unreleased/NDA-ed official content.

**Comment by lrzlin** [comment]
Merged in https://github.com/Cyan4973/xxHash/commit/9b1d788241c2534b60f485e2de7d185a983d1b59

**Comment by xen0n** [comment]
Congratulations!

**Comment by 24bit-xjkp** [comment]
I have add LASX support in https://github.com/Cyan4973/xxHash/pull/996 and it is approved.
