### ISSUE TITLE
gcc-15 compile llvm-18 error: use of undeclared identifier 'uint64_t'

### ISSUE THREAD

**Issue by Xinmudotmoe** [loongson-community/discussions#74]
经过测试和验证 这可能不是龙架构特有问题, 但是因为龙架构基线快速滚动, 导致较早暴露
运行 [AOSC-Dev/buildbot-benchmark](https://github.com/AOSC-Dev/buildbot-benchmark) 时发现的问题,但同样 并非AOSC特有.
在 *-*-linux-gnu 中 使用libstdc++-15(gcc-15提供) 构建llvm-18时,会有以下报错
```log
* /llvm-project/llvm/include/llvm/ADT/SmallVector.h:109:62: error: use of undeclared identifier 'uint64_t'
  109 |     std::conditional_t<sizeof(T) < 4 && sizeof(void *) >= 8, uint64_t,
```

# 问题链

在gcc-14中 使用以下的路径
```text
llvm/ADT/SmallVector.h:28
g++-v14/memory:71
g++-v14/bits/align.h:34
stdint.h:27
stdint-uintn.h
```
在gcc-15中 使用以下的路径
```text
llvm/ADT/SmallVector.h:28
g++-v15/memory:73
g++-v15/bits/align.h(改变 不再导入stdint.h和stdint-uintn.h)
```

# 可能影响的范围

对于依赖旧llvm或特定llvm版本的软件包,将可能面临无法构建的问题.

# 关联提交

https://github.com/gcc-mirror/gcc/commit/3a817a4a5a6d94da9127af3be9f84a74e3076ee2

**Comment by xry111** [comment]
请加 `#include <cstdint>`，只要 libstdc++ 清理头文件依赖就会爆出 114514 个这类问题。

显然是架构无关问题。

**Comment by Shylock-Hg** [comment]
> 请加 `#include <cstdint>`，只要 libstdc++ 清理头文件依赖就会爆出 114514 个这类问题。
> 
> 显然是架构无关问题。

我也遇到了同样问题，但是SmallVector.h已经包含`#include <cstdint>`

**Comment by Shylock-Hg** [comment]
> > 请加 `#include <cstdint>`，只要 libstdc++ 清理头文件依赖就会爆出 114514 个这类问题。
> > 显然是架构无关问题。
> 
> 我也遇到了同样问题，但是SmallVector.h已经包含`#include <cstdint>`

抱歉搞错了，clangd给我直接跳转到系统的llvm头文件了。。。
